# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='payment_date',
            field=models.DateTimeField(),
        ),
    ]
